# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
builds:
  - id: lesshero
    env:
      - CGO_ENABLED=0

dockers:
  - image_templates:
      - "hendry/{{.ProjectName}}"

brews:
  - name: lesshero
    repository:
      owner: kaihendry
      name: lesshero
    homepage: "https://github.com/kaihendry/lesshero"
    description: Highlight refactors and efforts to keep code base lean
    license: "MIT"
