# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lesshero < Formula
  desc "Highlight refactors and efforts to keep code base lean"
  homepage "https://github.com/kaihendry/lesshero"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kaihendry/lesshero/releases/download/v0.0.6/lesshero_0.0.6_darwin_arm64.tar.gz"
      sha256 "401dd44ee8b61e55230a2d1fea74fdd715fd0242a4ee5313746199bc1c9b3c24"

      def install
        bin.install "lesshero"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kaihendry/lesshero/releases/download/v0.0.6/lesshero_0.0.6_darwin_amd64.tar.gz"
      sha256 "8b1509601b6099d2e0fda020cbbe71e9b22745e7ebdbd6c8d97f8e8f08156e92"

      def install
        bin.install "lesshero"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kaihendry/lesshero/releases/download/v0.0.6/lesshero_0.0.6_linux_arm64.tar.gz"
      sha256 "3b47bcf0464f63e47b3f80606057341078d01c9634a8685875a884297d4649ec"

      def install
        bin.install "lesshero"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kaihendry/lesshero/releases/download/v0.0.6/lesshero_0.0.6_linux_amd64.tar.gz"
      sha256 "7aac925ebcd6e79f433a2657ca6a5bfad946f1eb8edc5c7eef729b2bc4f7db21"

      def install
        bin.install "lesshero"
      end
    end
  end
end
