# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lesshero < Formula
  desc "Highlight refactors and efforts to keep code base lean"
  homepage "https://github.com/kaihendry/lesshero"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kaihendry/lesshero/releases/download/v0.0.7/lesshero_0.0.7_darwin_amd64.tar.gz"
      sha256 "a0051474d04a03d461050a7ef845c3df7590aef8e09792a0938ce3276f49fa2f"

      def install
        bin.install "lesshero"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kaihendry/lesshero/releases/download/v0.0.7/lesshero_0.0.7_darwin_arm64.tar.gz"
      sha256 "25ba0300e5be9599e31ea5d682fce9f0a67214057f700431dc84e7c1ca46684b"

      def install
        bin.install "lesshero"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kaihendry/lesshero/releases/download/v0.0.7/lesshero_0.0.7_linux_amd64.tar.gz"
      sha256 "8701120114e1b276d8d67db561e11ce9b0a77a70c377a7d58d961b42dcb6dda5"

      def install
        bin.install "lesshero"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kaihendry/lesshero/releases/download/v0.0.7/lesshero_0.0.7_linux_arm64.tar.gz"
      sha256 "8db6419f581757d511a0379a88e5d55242da1cec5a423db1ce235ea6d20afe66"

      def install
        bin.install "lesshero"
      end
    end
  end
end
