# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lesshero < Formula
  desc "Highlight refactors and efforts to keep code base lean"
  homepage "https://github.com/kaihendry/lesshero"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kaihendry/lesshero/releases/download/v0.0.4/lesshero_0.0.4_darwin_amd64.tar.gz"
      sha256 "c9e83f924aa69ab82d3ac5da55b29bd11645fa018dffcf3646fca6f73d9bd115"

      def install
        bin.install "lesshero"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kaihendry/lesshero/releases/download/v0.0.4/lesshero_0.0.4_darwin_arm64.tar.gz"
      sha256 "b933314cb232fb43628cf54e130286b91fa75a392c1ae701fea8d6310d58ea6e"

      def install
        bin.install "lesshero"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kaihendry/lesshero/releases/download/v0.0.4/lesshero_0.0.4_linux_arm64.tar.gz"
      sha256 "33ecd752c0f65416c70e714cf99e44db815ae1e95ad02619110d8265342ad5e8"

      def install
        bin.install "lesshero"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kaihendry/lesshero/releases/download/v0.0.4/lesshero_0.0.4_linux_amd64.tar.gz"
      sha256 "1480938d327d117a4785496722a062e63e10feea63c3c03130d02286c4eee7b8"

      def install
        bin.install "lesshero"
      end
    end
  end
end
