name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version: 'stable'
      - name: Test
        run: go test -v ./...
      - name: build
        run: go build
      - name: show help
        run: ./lesshero -h
      - uses: golangci/golangci-lint-action@v6